import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Card } from "../components/Card.tsx";
import { useState, useEffect } from "react";

export default function Home() {
  // interface Data {
  //   cardData: String;

  // }
  const [cardData, setCardData] = useState();

  useEffect(() => {
    //getting all clothes
    fetch(`http://127.0.0.1:8000/clothes/`)
      .then((res) => res.json())
      .then((data) => {
        return setCardData(data);
      });
  }, []);

  if (!cardData) {
    return (
      <div>
        <p>Cargando...</p>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mayoral Proyect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {cardData.data.map((data, i) => {
          return (
            <Card
              key={i}
              img={data.img}
              name={data.name}
              prize={data.prize}
              strikedPrize={data.strikedPrize}
              salePrize={data.salePrize}
              colors={data.colors}
            />
          );
        })}
      </div>
    </div>
  );
}
